//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandaCadastro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int CompraId { get; set; }
        public string NomeCompra { get; set; }
        public double PrecoCompra { get; set; }
        public int ProdutoId { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
