//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstoqueProjeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public int VendaId { get; set; }
        public string NomeVenda { get; set; }
        public double PrecoVenda { get; set; }
        public int ProdutoId { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
